# 1. בדיקת הרשמה (Register) - יוצרת משתמש חדש במערכת
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
  "username": "YonatanTest",
  "email": "yonatan@test.com",
  "password": "password123"
}

###

# 2. בדיקת התחברות (Login) - מחזירה את הטוקן המאובטח (JWT)
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "email": "yonatan@test.com",
  "password": "password123"
}

###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI4N2M0OGE2YmQ3MjYyMzRjYzEwMDEiLCJ1c2VybmFtZSI6IllvbmF0YW5UZXN0IiwiaWF0IjoxNzg2MjYyODYzLCJleHAiOjE3ODYzMDYwNjN9.1v2aG12j71mIiOTas8px4RSqSbpw2fYJtG8md1aGYT8

# 3. בדיקת קניית מטבע (Buy Asset) - נתיב מוגן הדורש את הטוקן
POST http://localhost:5001/api/crypto/buy
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "coinId": "bitcoin",
  "symbol": "btc",
  "name": "Bitcoin",
  "quantity": 0.1
}

###

# 4. בדיקת צפייה בתיק ההשקעות (Get Portfolio) - פעולת Read מוגנת
GET http://localhost:5001/api/crypto/portfolio
Authorization: Bearer {{token}}


###

# 5. בדיקת מכירת מטבע (Sell Asset) - פעולת Update/Delete מוגנת
POST http://localhost:5001/api/crypto/sell
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "coinId": "bitcoin",
  "quantity": 0.3
}